project_id = "ihtffuincksucgewpjhq"

[functions.trainer-intake]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.generate-trainer-json]
verify_jwt = false

[functions.admin-fetch-submissions]
verify_jwt = false

[functions.admin-update-submission]
verify_jwt = false

[functions.enhance-trainer-content]
verify_jwt = false
